import fs from "node:fs";
import path from "node:path";
import { createClient } from "@sanity/client";
import { config as loadEnv } from "dotenv";
import { mapSanityPostsToBlogPosts } from "../lib/blog/map-post";
import { fetchBlogPostsFromSanity } from "../lib/blog/queries";

loadEnv({ path: ".env" });

function requireEnv(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) {
    throw new Error(`Missing required environment variable: ${name}`);
  }
  return value;
}

function createReadClient() {
  const token =
    process.env.SANITY_API_WRITE_TOKEN?.trim() ||
    process.env.SANITY_API_TOKEN?.trim();

  return createClient({
    projectId: requireEnv("SANITY_PROJECT_ID"),
    dataset: process.env.SANITY_DATASET?.trim() || "production",
    apiVersion: process.env.SANITY_API_VERSION?.trim() || "2024-01-01",
    token,
    useCdn: !token,
  });
}

function serializePostsFile(posts: ReturnType<typeof mapSanityPostsToBlogPosts>) {
  const serialized = JSON.stringify(posts, null, 2);
  return `// AUTO-GENERATED by npm run sanity:sync — do not edit manually.\nimport type { BlogPost } from "./blog-types";\n\nexport const blogPosts: BlogPost[] = ${serialized};\n`;
}

async function main() {
  const client = createReadClient();
  const records = await fetchBlogPostsFromSanity(client);

  if (!records.length) {
    throw new Error(
      "No posts returned from Sanity. Run npm run sanity:seed first.",
    );
  }

  const posts = mapSanityPostsToBlogPosts(records);
  const outputPath = path.join(process.cwd(), "app/data/blog-posts.data.ts");
  fs.writeFileSync(outputPath, serializePostsFile(posts), "utf8");
  console.log(
    `[sanity:sync] Wrote ${posts.length} posts to app/data/blog-posts.data.ts`,
  );
}

main().catch((error) => {
  console.error("[sanity:sync] Failed:", error);
  process.exit(1);
});
